apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: python-deploy 
  namespace: test-deploy
spec:
  repo: https://github.com/BulkMazurka/python-deploy.git
  branch: main
  paths:
    - .
  helm:
    releaseName: python-app   
