apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}-app
  {{- if and .Values.metrics.enabled .Values.metrics.path }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "{{ .Values.metrics.path }}"
    prometheus.io/port: "{{ .Values.metrics.port }}"
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-app
